#!/usr/bin/env python3
"""Generate ESLint package-boundary config from governance/ownership.toml."""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
import tomllib


HEADER = """// Generated by harness/depgraph/generate-ts-eslint-boundaries.py.
// Source of truth: governance/ownership.toml. Do not edit by hand.

"""


def load_json(path: pathlib.Path) -> dict:
    return json.loads(path.read_text())


def package_name_for_key(ownership_key: str) -> str:
    package_dir_name = ownership_key.rsplit("/", 1)[-1]
    return f"@asha/{package_dir_name}"


def load_actual_packages(repo: pathlib.Path) -> dict[str, tuple[str, pathlib.Path]]:
    package_root = repo / "ts" / "packages"
    actual: dict[str, tuple[str, pathlib.Path]] = {}
    for pkg_dir in sorted(package_root.iterdir()):
        if not pkg_dir.is_dir():
            continue
        pkg_json = pkg_dir / "package.json"
        if not pkg_json.exists():
            continue
        data = load_json(pkg_json)
        package_name = data.get("name")
        if package_name:
            actual[f"ts/packages/{pkg_dir.name}"] = (package_name, pkg_dir)
    return actual


def load_approved_export_subpaths(repo: pathlib.Path) -> dict[str, set[str]]:
    manifest_path = repo / "harness" / "public-surface" / "ts-packages.json"
    if not manifest_path.exists():
        return {}
    manifest = load_json(manifest_path)
    approved: dict[str, set[str]] = {}
    for record in manifest.get("packages", []):
        if not isinstance(record, dict):
            continue
        package_name = record.get("package")
        if not isinstance(package_name, str):
            continue
        approved[package_name] = {
            f"{package_name}/{subpath[2:]}"
            for subpath in record.get("allowedExportSubpaths", [])
            if isinstance(subpath, str) and subpath.startswith("./")
        }
    return approved


def render_config(repo: pathlib.Path) -> str:
    ownership_path = repo / "governance" / "ownership.toml"
    ownership = tomllib.loads(ownership_path.read_text())
    packages: dict[str, dict] = ownership.get("package", {})
    actual_packages = load_actual_packages(repo)
    ownership_exempt = set(ownership.get("ownership_exempt", {}).get("packages", []))
    approved_export_subpaths = load_approved_export_subpaths(repo)

    missing = [
        ownership_key
        for ownership_key in sorted(actual_packages)
        if ownership_key not in packages and ownership_key not in ownership_exempt
    ]
    if missing:
        joined = "\n".join(f"  - {ownership_key}" for ownership_key in missing)
        raise SystemExit(
            "Cannot generate ESLint package boundaries; missing ownership entries:\n"
            f"{joined}"
        )

    package_names_by_key = {
        ownership_key: package_name
        for ownership_key, (package_name, _pkg_dir) in actual_packages.items()
    }
    package_names_by_key.update(
        {
            ownership_key: package_name_for_key(ownership_key)
            for ownership_key in packages
            if ownership_key not in package_names_by_key
        }
    )
    all_package_names = sorted(package_names_by_key.values())

    configs = []
    for ownership_key in sorted(actual_packages):
        package_name, pkg_dir = actual_packages[ownership_key]
        pkg_meta = packages.get(ownership_key)
        if not pkg_meta:
            continue

        allowed = set(pkg_meta.get("may_import", []))
        pkg_lane = pkg_meta.get("lane", "?")
        restricted_paths = []
        restricted_patterns = []
        for target_name in all_package_names:
            if target_name == package_name:
                continue
            deep_message = (
                f"{ownership_key} must import {target_name} through its root barrel. "
                f"Do not import {target_name}/src, {target_name}/dist, generated internals, "
                "or other package-private files."
            )
            if target_name in allowed:
                group = [f"{target_name}/*"]
                for approved_subpath in sorted(approved_export_subpaths.get(target_name, set())):
                    group.append(f"!{approved_subpath}")
                restricted_patterns.append({"group": group, "message": deep_message})
                continue
            target_short = target_name.split("/", 1)[-1]
            target_lane = packages.get(f"ts/packages/{target_short}", {}).get("lane", "?")
            message = (
                f"{ownership_key} (lane {pkg_lane}) may not import {target_name} "
                f"(lane {target_lane}) unless governance/ownership.toml may_import "
                "allows it. Route through an approved public API or update ownership "
                "with reviewer context."
            )
            restricted_paths.append({"name": target_name, "message": message})
            restricted_patterns.append({"group": [f"{target_name}/*"], "message": message})

        if restricted_paths:
            configs.append(
                {
                    "files": [f"packages/{pkg_dir.name}/**/*.ts"],
                    "rules": {
                        "no-restricted-imports": [
                            "error",
                            {"paths": restricted_paths, "patterns": restricted_patterns},
                        ]
                    },
                }
            )

    return (
        HEADER
        + "const generatedBoundaryConfigs = "
        + json.dumps(configs, indent=2)
        + ";\n\nexport default generatedBoundaryConfigs;\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--repo-root",
        type=pathlib.Path,
        default=pathlib.Path(__file__).resolve().parents[2],
    )
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=None,
        help="Generated ESLint config path. Defaults to <repo>/ts/eslint-boundaries.generated.mjs.",
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    repo = args.repo_root.resolve()
    output = args.output or (repo / "ts" / "eslint-boundaries.generated.mjs")
    rendered = render_config(repo)

    if args.check:
        if not output.exists():
            print(f"FAIL: generated ESLint boundary config is missing: {output}")
            return 1
        current = output.read_text()
        if current != rendered:
            print(
                "FAIL: generated ESLint boundary config is stale. "
                "Run `python3 harness/depgraph/generate-ts-eslint-boundaries.py`."
            )
            return 1
        print("TypeScript ESLint boundary config: OK")
        return 0

    output.write_text(rendered)
    print(f"Wrote {output.relative_to(repo)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
