#!/usr/bin/env python3
"""Validate and update the ASHA Agent Code Atlas generated inventory."""
from __future__ import annotations

import argparse
import json
import os
import pathlib
import re
import sys
import tomllib
from collections import defaultdict
from typing import Any, NoReturn

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
ATLAS_INDEX = REPO_ROOT / "docs" / "agent-code-atlas.md"
CODE_MAP_DIR = REPO_ROOT / "docs" / "code-map"
GENERATED_INVENTORY = CODE_MAP_DIR / "generated-inventory.md"
OWNERSHIP_PATH = REPO_ROOT / "governance" / "ownership.toml"
PUBLIC_SURFACE_PATH = REPO_ROOT / "harness" / "public-surface" / "ts-packages.json"
BRIDGE_MANIFEST_PATH = (
    REPO_ROOT / "engine-rs" / "crates" / "bridge" / "runtime-bridge-api" / "bridge-manifest.toml"
)

REQUIRED_PAGE_SECTIONS = [
    "Purpose",
    "Owns",
    "Does Not Own",
    "Primary Paths",
    "Public Downstream Surfaces",
    "Private Or Forbidden Paths",
    "Proof Gates And Goldens",
    "Common Agent Mistakes",
    "Follow-up Routing",
]

IGNORED_LINK_PREFIXES = ("http://", "https://", "mailto:", "#")


def fail(message: str) -> NoReturn:
    print(f"FAIL: {message}")
    sys.exit(1)


def read_json(path: pathlib.Path) -> dict[str, Any]:
    return json.loads(path.read_text())


def read_toml(path: pathlib.Path) -> dict[str, Any]:
    return tomllib.loads(path.read_text())


def markdown_link_targets(markdown: str) -> list[str]:
    return re.findall(r"\[[^\]]+\]\(([^)]+)\)", markdown)


def local_link_path(target: str) -> str | None:
    target = target.strip()
    if not target or target.startswith(IGNORED_LINK_PREFIXES):
        return None
    if "://" in target:
        return None
    return target.split("#", 1)[0]


def validate_markdown_links(paths: list[pathlib.Path]) -> None:
    for path in paths:
        text = path.read_text()
        for target in markdown_link_targets(text):
            local_path_text = local_link_path(target)
            if not local_path_text:
                continue
            resolved = (path.parent / local_path_text).resolve()
            try:
                resolved.relative_to(REPO_ROOT)
            except ValueError:
                fail(f"{path.relative_to(REPO_ROOT)} links outside the repo: {target}")
            if not resolved.exists():
                fail(f"{path.relative_to(REPO_ROOT)} references missing path: {target}")


def atlas_pages() -> list[pathlib.Path]:
    if not CODE_MAP_DIR.is_dir():
        fail("docs/code-map is missing")
    pages = sorted(CODE_MAP_DIR.glob("*.md"))
    if GENERATED_INVENTORY not in pages:
        pages.append(GENERATED_INVENTORY)
    return [ATLAS_INDEX, *pages]


def validate_page_sections() -> None:
    hand_written_pages = [
        path for path in sorted(CODE_MAP_DIR.glob("*.md")) if path.name != GENERATED_INVENTORY.name
    ]
    if not hand_written_pages:
        fail("docs/code-map must contain handwritten lane/system pages")
    for path in hand_written_pages:
        text = path.read_text()
        for heading in REQUIRED_PAGE_SECTIONS:
            if f"## {heading}\n" not in text:
                fail(f"{path.relative_to(REPO_ROOT)} is missing required section: {heading}")


def crate_name(crate_path: str) -> str:
    cargo_path = REPO_ROOT / crate_path / "Cargo.toml"
    if not cargo_path.is_file():
        return crate_path.rsplit("/", 1)[-1]
    cargo = read_toml(cargo_path)
    package = cargo.get("package", {})
    name = package.get("name")
    if isinstance(name, str):
        return name
    return crate_path.rsplit("/", 1)[-1]


def package_name(package_path: str) -> str:
    package_path_obj = REPO_ROOT / package_path / "package.json"
    if not package_path_obj.is_file():
        return package_path.rsplit("/", 1)[-1]
    package = read_json(package_path_obj)
    name = package.get("name")
    if isinstance(name, str):
        return name
    return package_path.rsplit("/", 1)[-1]


def relative_link(from_path: pathlib.Path, to_path: pathlib.Path) -> str:
    return pathlib.Path(os.path.relpath(to_path, from_path.parent)).as_posix()


def inventory_header() -> list[str]:
    return [
        "<!-- GENERATED BY harness/code-map/check-agent-code-atlas.py; DO NOT EDIT BY HAND. -->",
        "# Agent Code Atlas Generated Inventory",
        "",
        "This file is regenerated from repo metadata and checked by",
        "`python3 harness/code-map/check-agent-code-atlas.py --check`.",
        "",
        "Source metadata:",
        f"- [governance/ownership.toml]({relative_link(GENERATED_INVENTORY, OWNERSHIP_PATH)})",
        f"- [harness/public-surface/ts-packages.json]({relative_link(GENERATED_INVENTORY, PUBLIC_SURFACE_PATH)})",
        f"- [runtime bridge manifest]({relative_link(GENERATED_INVENTORY, BRIDGE_MANIFEST_PATH)})",
        "",
    ]


def render_crate_inventory(ownership: dict[str, Any]) -> list[str]:
    crates_by_lane: dict[str, list[tuple[str, str, str]]] = defaultdict(list)
    for crate_path, record in ownership.get("crate", {}).items():
        lane = str(record.get("lane", "unknown"))
        status = str(record.get("implementation_status", "active"))
        crates_by_lane[lane].append((crate_name(crate_path), crate_path, status))

    lines = ["## Rust Crates By Lane", ""]
    for lane in sorted(crates_by_lane):
        crates = sorted(crates_by_lane[lane], key=lambda item: item[0])
        lines.append(f"### {lane} ({len(crates)})")
        lines.append("")
        for name, crate_path, status in crates:
            cargo_path = REPO_ROOT / crate_path / "Cargo.toml"
            lines.append(f"- [`{name}`]({relative_link(GENERATED_INVENTORY, cargo_path)}) — {status}")
        lines.append("")
    return lines


def render_package_inventory(ownership: dict[str, Any]) -> list[str]:
    packages_by_lane: dict[str, list[tuple[str, str, str]]] = defaultdict(list)
    for package_path, record in ownership.get("package", {}).items():
        lane = str(record.get("lane", "unknown"))
        status = str(record.get("implementation_status", "active"))
        packages_by_lane[lane].append((package_name(package_path), package_path, status))

    lines = ["## TypeScript Packages By Lane", ""]
    for lane in sorted(packages_by_lane):
        packages = sorted(packages_by_lane[lane], key=lambda item: item[0])
        lines.append(f"### {lane} ({len(packages)})")
        lines.append("")
        for name, package_path, status in packages:
            package_json_path = REPO_ROOT / package_path / "package.json"
            lines.append(f"- [`{name}`]({relative_link(GENERATED_INVENTORY, package_json_path)}) — {status}")
        lines.append("")
    return lines


def render_public_surface_inventory() -> list[str]:
    manifest = read_json(PUBLIC_SURFACE_PATH)
    records = sorted(manifest.get("packages", []), key=lambda record: record.get("package", ""))
    lines = ["## Public Surface Manifest Summary", ""]
    for record in records:
        package = record.get("package", "unknown")
        status = record.get("status", "unknown")
        roles = record.get("allowedConsumerRoles", [])
        role_text = ", ".join(roles) if roles else "none"
        ownership_key = record.get("ownershipKey")
        if isinstance(ownership_key, str):
            package_path = REPO_ROOT / ownership_key / "package.json"
            package_ref = f"[`{package}`]({relative_link(GENERATED_INVENTORY, package_path)})"
        else:
            package_ref = f"`{package}`"
        lines.append(f"- {package_ref} — {status}; roles: {role_text}")
    lines.append("")
    return lines


def render_bridge_inventory() -> list[str]:
    manifest = read_toml(BRIDGE_MANIFEST_PATH)
    operations = sorted(manifest.get("operation", []), key=lambda operation: operation.get("name", ""))
    lines = ["## Runtime Bridge Operation Summary", ""]
    lines.append(
        f"Source: [bridge-manifest.toml]({relative_link(GENERATED_INVENTORY, BRIDGE_MANIFEST_PATH)})"
    )
    lines.append("")
    for operation in operations:
        name = operation.get("name", "unknown")
        surface = operation.get("surface", "unknown")
        output = operation.get("output", "unknown")
        lines.append(f"- `{name}` — {surface}; output `{output}`")
    lines.append("")
    return lines


def render_evidence_inventory() -> list[str]:
    lines = ["## Evidence Entrypoints", ""]
    for root_name in ["fixtures", "goldens"]:
        root = REPO_ROOT / "harness" / root_name
        child_dirs = sorted(path for path in root.iterdir() if path.is_dir())
        lines.append(f"### harness/{root_name} ({len(child_dirs)} groups)")
        lines.append("")
        for child in child_dirs:
            file_count = len([path for path in child.rglob("*") if path.is_file()])
            lines.append(
                f"- [`{child.relative_to(REPO_ROOT).as_posix()}`]({relative_link(GENERATED_INVENTORY, child)}) — {file_count} files"
            )
        lines.append("")
    return lines


def generated_inventory() -> str:
    ownership = read_toml(OWNERSHIP_PATH)
    sections = [
        inventory_header(),
        render_crate_inventory(ownership),
        render_package_inventory(ownership),
        render_public_surface_inventory(),
        render_bridge_inventory(),
        render_evidence_inventory(),
    ]
    return "\n".join(line for section in sections for line in section).rstrip() + "\n"


def check_inventory(write: bool) -> None:
    expected = generated_inventory()
    if write:
        GENERATED_INVENTORY.write_text(expected)
        print(f"updated {GENERATED_INVENTORY.relative_to(REPO_ROOT)}")
        return
    if not GENERATED_INVENTORY.is_file():
        fail("generated inventory is missing; run python3 harness/code-map/check-agent-code-atlas.py --write")
    actual = GENERATED_INVENTORY.read_text()
    if actual != expected:
        fail("docs/code-map/generated-inventory.md is stale; run python3 harness/code-map/check-agent-code-atlas.py --write")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="rewrite the generated atlas inventory")
    parser.add_argument("--check", action="store_true", help="validate the atlas inventory and checked links")
    args = parser.parse_args()

    if not ATLAS_INDEX.is_file():
        fail("docs/agent-code-atlas.md is missing")

    check_inventory(write=args.write)
    validate_page_sections()
    validate_markdown_links(atlas_pages())
    print("Agent Code Atlas: OK")


if __name__ == "__main__":
    main()
