#!/usr/bin/env python3
"""Validate and update the ASHA Agent Code Atlas generated inventory."""
from __future__ import annotations

import argparse
import json
import os
import pathlib
import re
import sys
import tomllib
from collections import defaultdict
from typing import Any, NoReturn

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "harness" / "depgraph"))

from committed_paths import classify, report as committed_path_report, tracked_paths

ATLAS_INDEX = REPO_ROOT / "docs" / "agent-code-atlas.md"
CODE_MAP_DIR = REPO_ROOT / "docs" / "code-map"
GENERATED_INVENTORY = CODE_MAP_DIR / "generated-inventory.md"
OWNERSHIP_PATH = REPO_ROOT / "governance" / "ownership.toml"
PUBLIC_SURFACE_PATH = REPO_ROOT / "harness" / "public-surface" / "ts-packages.json"
RUST_PUBLIC_SURFACE_PATH = REPO_ROOT / "harness" / "public-surface" / "rust-crates.json"
RUST_SHAPE_POLICY = REPO_ROOT / "harness" / "depgraph" / "rust-source-shape-policy.json"
TS_SHAPE_POLICY = REPO_ROOT / "harness" / "depgraph" / "ts-source-shape-policy.json"
BRIDGE_MANIFEST_PATH = (
    REPO_ROOT / "engine-rs" / "crates" / "bridge" / "runtime-bridge-api" / "bridge-manifest.toml"
)

REQUIRED_PAGE_SECTIONS = [
    "Purpose",
    "Owns",
    "Does Not Own",
    "Primary Paths",
    "Public Downstream Surfaces",
    "Private Or Forbidden Paths",
    "Proof Gates And Goldens",
    "Common Agent Mistakes",
    "Follow-up Routing",
]

IGNORED_LINK_PREFIXES = ("http://", "https://", "mailto:", "#")


def fail(message: str) -> NoReturn:
    print(f"FAIL: {message}")
    sys.exit(1)


def read_json(path: pathlib.Path) -> dict[str, Any]:
    return json.loads(path.read_text())


def read_toml(path: pathlib.Path) -> dict[str, Any]:
    return tomllib.loads(path.read_text())


def markdown_link_targets(markdown: str) -> list[str]:
    return re.findall(r"\[[^\]]+\]\(([^)]+)\)", markdown)


def local_link_path(target: str) -> str | None:
    target = target.strip()
    if not target or target.startswith(IGNORED_LINK_PREFIXES):
        return None
    if "://" in target:
        return None
    return target.split("#", 1)[0]


def validate_markdown_links(paths: list[pathlib.Path]) -> None:
    for path in paths:
        text = path.read_text()
        for target in markdown_link_targets(text):
            local_path_text = local_link_path(target)
            if not local_path_text:
                continue
            resolved = (path.parent / local_path_text).resolve()
            try:
                resolved.relative_to(REPO_ROOT)
            except ValueError:
                fail(f"{path.relative_to(REPO_ROOT)} links outside the repo: {target}")
            if not resolved.exists():
                fail(f"{path.relative_to(REPO_ROOT)} references missing path: {target}")


def atlas_pages() -> list[pathlib.Path]:
    if not CODE_MAP_DIR.is_dir():
        fail("docs/code-map is missing")
    pages = sorted(CODE_MAP_DIR.glob("*.md"))
    if GENERATED_INVENTORY not in pages:
        pages.append(GENERATED_INVENTORY)
    return [ATLAS_INDEX, *pages]


def validate_page_sections() -> None:
    hand_written_pages = [
        path for path in sorted(CODE_MAP_DIR.glob("*.md")) if path.name != GENERATED_INVENTORY.name
    ]
    if not hand_written_pages:
        fail("docs/code-map must contain handwritten lane/system pages")
    for path in hand_written_pages:
        text = path.read_text()
        for heading in REQUIRED_PAGE_SECTIONS:
            if f"## {heading}\n" not in text:
                fail(f"{path.relative_to(REPO_ROOT)} is missing required section: {heading}")


def crate_name(crate_path: str) -> str:
    cargo_path = REPO_ROOT / crate_path / "Cargo.toml"
    if not cargo_path.is_file():
        return crate_path.rsplit("/", 1)[-1]
    cargo = read_toml(cargo_path)
    package = cargo.get("package", {})
    name = package.get("name")
    if isinstance(name, str):
        return name
    return crate_path.rsplit("/", 1)[-1]


def package_name(package_path: str) -> str:
    package_path_obj = REPO_ROOT / package_path / "package.json"
    if not package_path_obj.is_file():
        return package_path.rsplit("/", 1)[-1]
    package = read_json(package_path_obj)
    name = package.get("name")
    if isinstance(name, str):
        return name
    return package_path.rsplit("/", 1)[-1]


def relative_link(from_path: pathlib.Path, to_path: pathlib.Path) -> str:
    return pathlib.Path(os.path.relpath(to_path, from_path.parent)).as_posix()


def inventory_header() -> list[str]:
    return [
        "<!-- GENERATED BY harness/code-map/check-agent-code-atlas.py; DO NOT EDIT BY HAND. -->",
        "# Agent Code Atlas Generated Inventory",
        "",
        "This file is regenerated from repo metadata and checked by",
        "`python3 harness/code-map/check-agent-code-atlas.py --check`.",
        "",
        "Source metadata:",
        f"- [governance/ownership.toml]({relative_link(GENERATED_INVENTORY, OWNERSHIP_PATH)})",
        f"- [harness/public-surface/ts-packages.json]({relative_link(GENERATED_INVENTORY, PUBLIC_SURFACE_PATH)})",
        f"- [harness/public-surface/rust-crates.json]({relative_link(GENERATED_INVENTORY, RUST_PUBLIC_SURFACE_PATH)})",
        f"- [runtime bridge manifest]({relative_link(GENERATED_INVENTORY, BRIDGE_MANIFEST_PATH)})",
        "",
    ]


def render_crate_inventory(ownership: dict[str, Any]) -> list[str]:
    crates_by_lane: dict[str, list[tuple[str, str, str]]] = defaultdict(list)
    for crate_path, record in ownership.get("crate", {}).items():
        lane = str(record.get("lane", "unknown"))
        status = str(record.get("implementation_status", "active"))
        crates_by_lane[lane].append((crate_name(crate_path), crate_path, status))

    lines = ["## Rust Crates By Lane", ""]
    for lane in sorted(crates_by_lane):
        crates = sorted(crates_by_lane[lane], key=lambda item: item[0])
        lines.append(f"### {lane} ({len(crates)})")
        lines.append("")
        for name, crate_path, status in crates:
            cargo_path = REPO_ROOT / crate_path / "Cargo.toml"
            lines.append(f"- [`{name}`]({relative_link(GENERATED_INVENTORY, cargo_path)}) — {status}")
        lines.append("")
    return lines


def render_package_inventory(ownership: dict[str, Any]) -> list[str]:
    packages_by_lane: dict[str, list[tuple[str, str, str]]] = defaultdict(list)
    for package_path, record in ownership.get("package", {}).items():
        lane = str(record.get("lane", "unknown"))
        status = str(record.get("implementation_status", "active"))
        packages_by_lane[lane].append((package_name(package_path), package_path, status))

    lines = ["## TypeScript Packages By Lane", ""]
    for lane in sorted(packages_by_lane):
        packages = sorted(packages_by_lane[lane], key=lambda item: item[0])
        lines.append(f"### {lane} ({len(packages)})")
        lines.append("")
        for name, package_path, status in packages:
            package_json_path = REPO_ROOT / package_path / "package.json"
            lines.append(f"- [`{name}`]({relative_link(GENERATED_INVENTORY, package_json_path)}) — {status}")
        lines.append("")
    return lines


def render_public_surface_inventory() -> list[str]:
    manifest = read_json(PUBLIC_SURFACE_PATH)
    records = sorted(manifest.get("packages", []), key=lambda record: record.get("package", ""))
    lines = ["## Public Surface Manifest Summary", ""]
    for record in records:
        package = record.get("package", "unknown")
        status = record.get("status", "unknown")
        roles = record.get("allowedConsumerRoles", [])
        role_text = ", ".join(roles) if roles else "none"
        ownership_key = record.get("ownershipKey")
        if isinstance(ownership_key, str):
            package_path = REPO_ROOT / ownership_key / "package.json"
            package_ref = f"[`{package}`]({relative_link(GENERATED_INVENTORY, package_path)})"
        else:
            package_ref = f"`{package}`"
        lines.append(f"- {package_ref} — {status}; roles: {role_text}")
    lines.append("")
    return lines


def render_bridge_inventory() -> list[str]:
    manifest = read_toml(BRIDGE_MANIFEST_PATH)
    operations = sorted(manifest.get("operation", []), key=lambda operation: operation.get("name", ""))
    lines = ["## Runtime Bridge Operation Summary", ""]
    lines.append(
        f"Source: [bridge-manifest.toml]({relative_link(GENERATED_INVENTORY, BRIDGE_MANIFEST_PATH)})"
    )
    lines.append("")
    for operation in operations:
        name = operation.get("name", "unknown")
        surface = operation.get("surface", "unknown")
        output = operation.get("output", "unknown")
        lines.append(f"- `{name}` — {surface}; output `{output}`")
    lines.append("")
    return lines


def render_evidence_inventory() -> list[str]:
    lines = ["## Evidence Entrypoints", ""]
    for root_name in ["fixtures", "goldens"]:
        root = REPO_ROOT / "harness" / root_name
        child_dirs = sorted(path for path in root.iterdir() if path.is_dir())
        lines.append(f"### harness/{root_name} ({len(child_dirs)} groups)")
        lines.append("")
        for child in child_dirs:
            file_count = len([path for path in child.rglob("*") if path.is_file()])
            lines.append(
                f"- [`{child.relative_to(REPO_ROOT).as_posix()}`]({relative_link(GENERATED_INVENTORY, child)}) — {file_count} files"
            )
        lines.append("")
    return lines


def normalized(name: str) -> str:
    return name.replace("_", "-")


def dependency_names(cargo: dict[str, Any]) -> set[str]:
    names: set[str] = set()
    for section in ("dependencies", "dev-dependencies", "build-dependencies"):
        for dependency, value in cargo.get(section, {}).items():
            package = value.get("package", dependency) if isinstance(value, dict) else dependency
            names.add(normalized(package))
    return names


def rust_dependency_cells(ownership: dict[str, Any]) -> dict[str, dict[str, Any]]:
    records = ownership.get("crate", {})
    name_by_path = {path: normalized(crate_name(path)) for path in records}
    internal_names = set(name_by_path.values())
    cells: dict[str, dict[str, Any]] = {}
    for path, record in records.items():
        name = name_by_path[path]
        cargo_path = REPO_ROOT / path / "Cargo.toml"
        actual = dependency_names(read_toml(cargo_path)) & internal_names if cargo_path.is_file() else set()
        configured = record.get("may_depend_on", [])
        allowed = (
            internal_names - {name}
            if configured == "unrestricted"
            else {normalized(item) for item in configured} & internal_names
        )
        cells[name] = {
            "name": name,
            "path": path,
            "lane": record.get("lane", "unknown"),
            "actual": actual,
            "allowed": allowed,
        }
    return cells


def ts_source_imports(package_path: pathlib.Path) -> set[str]:
    imports: set[str] = set()
    source = package_path / "src"
    if not source.is_dir():
        return imports
    pattern = re.compile(
        r"(?:from\s+|import\s+(?:type\s+)?|import\s*\(\s*)"
        r"[\"'](@asha/[a-z0-9-]+)(?:/[^\"']*)?[\"']"
    )
    for path in source.rglob("*.ts"):
        imports.update(match.group(1) for match in pattern.finditer(path.read_text()))
    return imports


def ts_dependency_cells(ownership: dict[str, Any]) -> dict[str, dict[str, Any]]:
    records = ownership.get("package", {})
    name_by_path = {path: package_name(path) for path in records}
    internal_names = set(name_by_path.values())
    cells: dict[str, dict[str, Any]] = {}
    for path, record in records.items():
        name = name_by_path[path]
        package_path = REPO_ROOT / path
        package_json = package_path / "package.json"
        manifest_dependencies: set[str] = set()
        if package_json.is_file():
            manifest = read_json(package_json)
            for section in ("dependencies", "devDependencies", "peerDependencies"):
                manifest_dependencies.update(manifest.get(section, {}))
        actual = (manifest_dependencies | ts_source_imports(package_path)) & internal_names - {name}
        configured = record.get("may_import", [])
        allowed = (
            internal_names - {name}
            if configured == "unrestricted"
            else set(configured) & internal_names
        )
        cells[name] = {
            "name": name,
            "path": path,
            "lane": record.get("lane", "unknown"),
            "actual": actual,
            "allowed": allowed,
        }
    return cells


def has_path(graph: dict[str, set[str]], start: str, target: str) -> bool:
    pending = list(graph.get(start, set()))
    seen: set[str] = set()
    while pending:
        current = pending.pop()
        if current == target:
            return True
        if current in seen:
            continue
        seen.add(current)
        pending.extend(graph.get(current, set()))
    return False


def public_consumer_roles() -> tuple[dict[str, list[str]], dict[str, list[str]]]:
    ts_roles = {
        item["package"]: item.get("allowedConsumerRoles", [])
        for item in read_json(PUBLIC_SURFACE_PATH).get("packages", [])
    }
    rust_roles: dict[str, list[str]] = {}
    for item in read_json(RUST_PUBLIC_SURFACE_PATH).get("crates", []):
        source = item.get("sourceOfTruth")
        if isinstance(source, str):
            rust_roles[normalized(crate_name(source))] = item.get("allowedConsumerRoles", [])
    return rust_roles, ts_roles


def render_dependency_table(
    title: str,
    cells: dict[str, dict[str, Any]],
    public_roles: dict[str, list[str]],
) -> list[str]:
    incoming = {name: set() for name in cells}
    actual_graph = {name: set(cell["actual"]) for name, cell in cells.items()}
    allowed_graph = {name: set(cell["allowed"]) for name, cell in cells.items()}
    for source, targets in actual_graph.items():
        for target in targets:
            incoming.setdefault(target, set()).add(source)
    lines = [f"### {title}", ""]
    lines.append("| Cell | Actual edges / allowed edges | Fan in/out | Cycle risk | Public consumers |")
    lines.append("|---|---|---:|---|---|")
    for name in sorted(cells):
        cell = cells[name]
        actual = ", ".join(f"`{item}`" for item in sorted(cell["actual"])) or "none"
        allowed = ", ".join(f"`{item}`" for item in sorted(cell["allowed"])) or "none"
        actual_cycle = any(has_path(actual_graph, target, name) for target in cell["actual"])
        mutual_allowed = any(name in allowed_graph.get(target, set()) for target in cell["allowed"])
        cycle_risk = "actual cycle" if actual_cycle else "mutual allowance" if mutual_allowed else "none"
        internal = sorted(incoming.get(name, set()))
        external = [f"role:{role}" for role in public_roles.get(name, [])]
        consumers = ", ".join(f"`{item}`" for item in [*internal, *external]) or "none"
        lines.append(
            f"| `{name}` ({cell['lane']}) | actual: {actual}<br>allowed: {allowed} | "
            f"{len(internal)}/{len(cell['actual'])} | {cycle_risk} | {consumers} |"
        )
    lines.append("")
    return lines


def ownership_for_source(path: str, ownership: dict[str, Any]) -> str:
    candidates = [
        (prefix, record.get("lane", "unknown"))
        for family in ("crate", "package")
        for prefix, record in ownership.get(family, {}).items()
        if path.startswith(prefix + "/")
    ]
    return max(candidates, key=lambda item: len(item[0]))[1] if candidates else "unowned"


def source_hotspots(ownership: dict[str, Any]) -> list[dict[str, Any]]:
    hotspots: list[dict[str, Any]] = []
    configurations = [
        (REPO_ROOT / "engine-rs", ".rs", read_json(RUST_SHAPE_POLICY)),
        (REPO_ROOT / "ts" / "packages", ".ts", read_json(TS_SHAPE_POLICY)),
    ]
    for root, suffix, policy in configurations:
        exemptions = {
            **policy.get("fileLineExemptions", {}),
            **policy.get("rootBarrelExemptions", {}),
        }
        for path in root.rglob(f"*{suffix}"):
            rel = path.relative_to(REPO_ROOT).as_posix()
            if classify(rel) != "committedSource":
                continue
            lines = len(path.read_text().splitlines()) + 1
            exemption = exemptions.get(rel)
            cap = exemption["maxLines"] if exemption else policy["maxSourceLines"]
            warning = exemption["warningLines"] if exemption else policy["warningSourceLines"]
            if lines < warning:
                continue
            hotspots.append({
                "path": rel,
                "lines": lines,
                "warning": warning,
                "cap": cap,
                "owner": exemption.get("owner") if exemption else ownership_for_source(rel, ownership),
                "reviewBy": exemption.get("reviewBy", "global policy") if exemption else "global policy",
            })
    return sorted(hotspots, key=lambda item: (-item["lines"] / item["cap"], item["path"]))


def render_structure_pressure(ownership: dict[str, Any]) -> list[str]:
    path_report = committed_path_report(tracked_paths(REPO_ROOT))
    if path_report["buildCacheOutputPaths"]:
        fail("tracked build/cache/output paths must be removed before generating architecture pressure")
    counts = path_report["counts"]
    rust_roles, ts_roles = public_consumer_roles()
    lines = ["## Assignment And Dependency Pressure", ""]
    lines.append(
        "Committed path classes: "
        f"{counts['committedSource']} source; {counts['generatedSource']} generated source; "
        f"{counts['otherCommitted']} other; {counts['buildCacheOutput']} build/cache/output."
    )
    lines.append("")
    lines.extend(render_dependency_table("Rust actual and allowed edges", rust_dependency_cells(ownership), rust_roles))
    lines.extend(render_dependency_table("TypeScript actual and allowed edges", ts_dependency_cells(ownership), ts_roles))
    lines.extend(["### Near-cap source hotspots", ""])
    lines.append("| Source | Lines / warning / cap | Owner | Review by |")
    lines.append("|---|---:|---|---|")
    for item in source_hotspots(ownership):
        lines.append(
            f"| `{item['path']}` | {item['lines']} / {item['warning']} / {item['cap']} | "
            f"{item['owner']} | {item['reviewBy']} |"
        )
    lines.append("")
    return lines


def generated_inventory() -> str:
    ownership = read_toml(OWNERSHIP_PATH)
    sections = [
        inventory_header(),
        render_crate_inventory(ownership),
        render_package_inventory(ownership),
        render_public_surface_inventory(),
        render_bridge_inventory(),
        render_structure_pressure(ownership),
        render_evidence_inventory(),
    ]
    return "\n".join(line for section in sections for line in section).rstrip() + "\n"


def check_inventory(write: bool) -> None:
    expected = generated_inventory()
    if write:
        GENERATED_INVENTORY.write_text(expected)
        print(f"updated {GENERATED_INVENTORY.relative_to(REPO_ROOT)}")
        return
    if not GENERATED_INVENTORY.is_file():
        fail("generated inventory is missing; run python3 harness/code-map/check-agent-code-atlas.py --write")
    actual = GENERATED_INVENTORY.read_text()
    if actual != expected:
        fail("docs/code-map/generated-inventory.md is stale; run python3 harness/code-map/check-agent-code-atlas.py --write")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="rewrite the generated atlas inventory")
    parser.add_argument("--check", action="store_true", help="validate the atlas inventory and checked links")
    args = parser.parse_args()

    if not ATLAS_INDEX.is_file():
        fail("docs/agent-code-atlas.md is missing")

    check_inventory(write=args.write)
    validate_page_sections()
    validate_markdown_links(atlas_pages())
    print("Agent Code Atlas: OK")


if __name__ == "__main__":
    main()
