#!/usr/bin/env python3
"""Generate mechanical bridge surfaces from the curated bridge manifest.

Semantic validation, native conversion, authority lookup, and mutation stay in
their owning handwritten Rust/TypeScript modules. This emitter owns only the
reviewable parity surfaces: operation descriptors, capability interfaces,
native export declarations/inventories, and Rust binding metadata.
"""

from __future__ import annotations

import json
import pathlib
import sys
import tomllib
from typing import Any

REPO = pathlib.Path(__file__).resolve().parents[2]
MANIFEST = REPO / "engine-rs/crates/bridge/runtime-bridge-api/bridge-manifest.toml"

OPS_TS = REPO / "ts/packages/runtime-bridge/src/generated/operations.ts"
SURFACES_TS = REPO / "ts/packages/runtime-bridge/src/generated/surfaces.ts"
CONF_JSON = REPO / "ts/packages/runtime-bridge/src/generated/conformance.json"
NATIVE_SURFACE_TS = REPO / "ts/packages/native-bridge/src/generated/addon-surface.ts"
RUST_OPERATIONS = REPO / "engine-rs/crates/bridge/runtime-bridge-api/src/generated/mod.rs"
RUST_NATIVE_EXPORTS = REPO / "engine-rs/crates/bridge/native-bridge/src/generated/mod.rs"
EXPORTS_MD = REPO / "engine-rs/crates/bridge/native-bridge/src/generated/EXPORTS.md"

TS_BANNER = (
    "// @generated by harness/codegen/bridge-emit.py — DO NOT EDIT.\n"
    "// Source of truth: engine-rs/crates/bridge/runtime-bridge-api/bridge-manifest.toml\n"
    "// Regenerate: python3 harness/codegen/bridge-emit.py --write\n"
)
RUST_BANNER = (
    "// @generated by harness/codegen/bridge-emit.py — DO NOT EDIT.\n"
    "// Source of truth: engine-rs/crates/bridge/runtime-bridge-api/bridge-manifest.toml\n"
)

PROTOCOL_WIRE_MODULES = {
    "protocol_diagnostics": "diagnostics",
    "protocol_game_rules": "gameRules",
    "protocol_input": "input",
    "protocol_presentation": "presentation",
    "protocol_render": "render",
    "protocol_scene": "scene",
    "protocol_time_control": "timeControl",
    "protocol_view": "view",
    "protocol_voxel": "voxel",
    "protocol_voxel_annotation": "voxelAnnotation",
    "protocol_voxel_asset": "voxelAsset",
    "protocol_voxel_conversion": "voxelConversion",
    "protocol_voxel_edit_history": "voxelEditHistory",
}
CONTRACT_WIRE_MODULES = {"RenderFrameDiff": "render"}


def snake_to_camel(name: str) -> str:
    head, *rest = name.split("_")
    return head + "".join(part.capitalize() for part in rest)


def facade_method(operation: dict[str, Any]) -> str:
    return operation.get("facade_method") or snake_to_camel(operation["name"])


def load_manifest() -> tuple[dict[str, Any], list[dict[str, Any]], list[dict[str, Any]]]:
    with MANIFEST.open("rb") as source:
        document = tomllib.load(source)
    manifest = document.get("manifest", {})
    operations = document.get("operation", [])
    capabilities = document.get("capability", [])
    validate_model(manifest, operations, capabilities)
    return manifest, operations, capabilities


def validate_model(
    manifest: dict[str, Any],
    operations: list[dict[str, Any]],
    capabilities: list[dict[str, Any]],
) -> None:
    operation_names = [operation.get("name") for operation in operations]
    if len(operation_names) != len(set(operation_names)):
        raise ValueError("bridge manifest operation names must be unique")
    capability_ids = [capability.get("id") for capability in capabilities]
    capability_interfaces = [capability.get("interface") for capability in capabilities]
    capability_properties = [capability.get("property") for capability in capabilities]
    for label, values in (
        ("ids", capability_ids),
        ("interfaces", capability_interfaces),
        ("properties", capability_properties),
    ):
        if len(values) != len(set(values)):
            raise ValueError(f"bridge capability {label} must be unique")
    grouped = [name for capability in capabilities for name in capability.get("operations", [])]
    missing = sorted(set(operation_names) - set(grouped))
    unknown = sorted(set(grouped) - set(operation_names))
    duplicate = sorted({name for name in grouped if grouped.count(name) > 1})
    if missing or unknown or duplicate:
        raise ValueError(
            "bridge capability coverage mismatch: "
            f"missing={missing}, unknown={unknown}, duplicate={duplicate}"
        )
    required_capability_fields = {
        "id", "interface", "property", "initialization", "project_bundle",
        "snapshot_hash", "resource_lifetime", "operations",
    }
    for capability in capabilities:
        absent = sorted(required_capability_fields - set(capability))
        if absent:
            raise ValueError(f"capability {capability.get('id')} is missing {absent}")
    error_families = manifest.get("error_families", [])
    if not error_families or len(error_families) != len(set(error_families)):
        raise ValueError("manifest.error_families must be a non-empty unique list")
    for field in ("default_max_input_bytes", "default_max_output_bytes"):
        value = manifest.get(field)
        if not isinstance(value, int) or value <= 0:
            raise ValueError(f"manifest.{field} must be a positive integer")
    for operation in operations:
        for field in ("max_input_bytes", "max_output_bytes"):
            value = operation.get(field)
            if value is not None and (not isinstance(value, int) or value <= 0):
                raise ValueError(f"operation {operation.get('name')} {field} must be positive")


def operation_capabilities(capabilities: list[dict[str, Any]]) -> dict[str, str]:
    return {
        operation: capability["id"]
        for capability in capabilities
        for operation in capability["operations"]
    }


def wire_type_ref(operation: dict[str, Any], field: str) -> tuple[str, str, bool]:
    reference = operation.get(f"facade_{field}") or operation[field]
    repeated = reference.endswith("[]")
    if repeated:
        reference = reference[:-2]
    if reference == "Unit":
        return "unit", "Unit", repeated
    if "::" not in reference:
        owner = (
            "handle"
            if reference.endswith("Handle") or reference == "FrameCursor"
            else "custom"
        )
        return owner, reference, repeated
    namespace, type_name = reference.split("::", 1)
    if namespace in PROTOCOL_WIRE_MODULES:
        return "generated", f"{PROTOCOL_WIRE_MODULES[namespace]}.{type_name}", repeated
    if namespace == "contracts" and type_name in CONTRACT_WIRE_MODULES:
        return "generated", f"{CONTRACT_WIRE_MODULES[type_name]}.{type_name}", repeated
    return "custom", type_name, repeated


def emit_operations_ts(
    manifest: dict[str, Any],
    operations: list[dict[str, Any]],
    capabilities: list[dict[str, Any]],
) -> str:
    capability_by_operation = operation_capabilities(capabilities)
    lines = [TS_BANNER, ""]
    lines.append("export type BridgeSurface = 'stable' | 'quarantined';")
    lines.append("export type BridgeErrorFamily =")
    for index, family in enumerate(manifest["error_families"]):
        suffix = ";" if index == len(manifest["error_families"]) - 1 else ""
        lines.append(f"  | '{family}'{suffix}")
    lines.extend([
        "",
        "export interface BridgeOperation {",
        "  readonly capability: string;",
        "  readonly errors: string;",
        "  readonly facadeMethod: string;",
        "  readonly input: string;",
        "  readonly inputWire: BridgeWireTypeRef;",
        "  readonly manifestName: string;",
        "  readonly maxInputBytes: number;",
        "  readonly maxOutputBytes: number;",
        "  readonly nativeWired: boolean;",
        "  readonly output: string;",
        "  readonly outputWire: BridgeWireTypeRef;",
        "  readonly surface: BridgeSurface;",
        "}",
        "",
        "export interface BridgeWireTypeRef {",
        "  readonly name: string;",
        "  readonly owner: 'custom' | 'generated' | 'handle' | 'unit';",
        "  readonly repeated: boolean;",
        "}",
        "",
        "const BRIDGE_OPERATION_DESCRIPTORS = [",
    ])
    for operation in operations:
        input_owner, input_name, input_repeated = wire_type_ref(operation, "input")
        output_owner, output_name, output_repeated = wire_type_ref(operation, "output")
        lines.append("  {")
        lines.append(f"    capability: '{capability_by_operation[operation['name']]}',")
        lines.append(f"    errors: '{operation['errors']}',")
        lines.append(f"    facadeMethod: '{facade_method(operation)}',")
        lines.append(f"    input: '{operation['input']}',")
        lines.append(
            f"    inputWire: {{ name: '{input_name}', owner: '{input_owner}', "
            f"repeated: {str(input_repeated).lower()} }},"
        )
        lines.append(f"    manifestName: '{operation['name']}',")
        lines.append(
            f"    maxInputBytes: {operation.get('max_input_bytes', manifest['default_max_input_bytes'])},"
        )
        lines.append(
            f"    maxOutputBytes: {operation.get('max_output_bytes', manifest['default_max_output_bytes'])},"
        )
        lines.append(f"    nativeWired: {str(operation['surface'] == 'stable').lower()},")
        lines.append(f"    output: '{operation['output']}',")
        lines.append(
            f"    outputWire: {{ name: '{output_name}', owner: '{output_owner}', "
            f"repeated: {str(output_repeated).lower()} }},"
        )
        lines.append(f"    surface: '{operation['surface']}',")
        lines.append("  },")
    lines.extend([
        "] as const satisfies readonly BridgeOperation[];",
        "",
        "export type BridgeOperationDescriptor = (typeof BRIDGE_OPERATION_DESCRIPTORS)[number];",
        "export const MANIFEST_OPERATIONS: readonly BridgeOperation[] = BRIDGE_OPERATION_DESCRIPTORS;",
        "",
        "export const NATIVE_WIRED_OPERATIONS: ReadonlySet<string> = new Set(",
        "  BRIDGE_OPERATION_DESCRIPTORS.filter((operation) => operation.nativeWired).map(",
        "    (operation) => operation.manifestName,",
        "  ),",
        ");",
        "",
    ])
    return "\n".join(lines)


def facade_type(operation: dict[str, Any], field: str) -> str | None:
    override = operation.get(f"facade_{field}")
    reference = override or operation[field]
    if reference == "Unit":
        return None
    repeated = reference.endswith("[]")
    if repeated:
        reference = reference[:-2]
    if "::" not in reference:
        if reference in {"EngineHandle", "FrameCursor"}:
            result = f"Session.{reference}"
        else:
            result = f"Bridge.{reference}"
    else:
        namespace, type_name = reference.split("::", 1)
        if namespace == "bridge":
            result = f"Bridge.{type_name}"
        elif namespace == "contracts":
            result = f"Contracts.{type_name}"
        elif namespace == "session" or namespace == "protocol_runtime":
            result = f"Session.{type_name}"
        else:
            result = f"Contracts.{type_name}"
    return f"readonly {result}[]" if repeated else result


def emit_surfaces_ts(
    operations: list[dict[str, Any]],
    capabilities: list[dict[str, Any]],
) -> str:
    operation_by_name = {operation["name"]: operation for operation in operations}
    lines = [
        TS_BANNER,
        "",
        "import type * as Contracts from '@asha/contracts';",
        "import type * as Session from '@asha/runtime-session';",
        "import type * as Bridge from '../bridge.js';",
        "",
    ]
    for capability in capabilities:
        lines.append(f"export interface {capability['interface']} {{")
        for name in capability["operations"]:
            operation = operation_by_name[name]
            input_type = facade_type(operation, "input")
            output_type = facade_type(operation, "output") or "void"
            arguments = "" if input_type is None else f"input: {input_type}"
            lines.append(f"  {facade_method(operation)}({arguments}): {output_type};")
        lines.extend(["}", ""])
    interfaces = ",\n    ".join(capability["interface"] for capability in capabilities)
    lines.extend([
        "/** Bounded generated verbs only; no generic method-name dispatcher. */",
        "export interface RuntimeBridge",
        f"  extends {interfaces} {{}}",
        "",
        "export interface RuntimeBridgePorts {",
    ])
    for capability in capabilities:
        lines.append(f"  readonly {capability['property']}: {capability['interface']};")
    lines.extend([
        "}",
        "",
        "export type RuntimeBridgePortId = keyof RuntimeBridgePorts;",
        "",
        "export interface RuntimeBridgePortContract {",
        "  readonly initialization: 'requiresEngine' | 'createsEngine';",
        "  readonly projectBundle: 'retainedAcrossLoadUnload' | 'ownsLoadUnload';",
        "  readonly snapshotHash:",
    ])
    snapshot_values = [capability["snapshot_hash"] for capability in capabilities]
    for index, value in enumerate(snapshot_values):
        suffix = ";" if index == len(snapshot_values) - 1 else ""
        lines.append(f"    | '{value}'{suffix}")
    lines.extend([
        "  readonly resourceLifetime: 'session' | 'frame' | 'mixedExplicitAndSession';",
        "}",
        "",
        "export const RUNTIME_BRIDGE_PORT_CONTRACTS: Readonly<",
        "  Record<RuntimeBridgePortId, RuntimeBridgePortContract>",
        "> = {",
    ])
    for capability in capabilities:
        lines.extend([
            f"  {capability['property']}: {{",
            f"    initialization: '{capability['initialization']}',",
            f"    projectBundle: '{capability['project_bundle']}',",
            f"    resourceLifetime: '{capability['resource_lifetime']}',",
            f"    snapshotHash: '{capability['snapshot_hash']}',",
            "  },",
        ])
    lines.extend([
        "};",
        "",
        "export function runtimeBridgePorts(bridge: RuntimeBridge): RuntimeBridgePorts {",
        "  return {",
    ])
    for capability in capabilities:
        lines.append(f"    {capability['property']}: bridge,")
    lines.extend(["  };", "}", ""])
    return "\n".join(lines)


def emit_native_surface_ts(operations: list[dict[str, Any]]) -> str:
    stable_methods = [facade_method(operation) for operation in operations if operation["surface"] == "stable"]
    lines = [TS_BANNER, "", "const GENERATED_NATIVE_ADDON_EXPORT_NAMES = ["]
    lines.extend(f"  '{method}'," for method in stable_methods)
    lines.extend([
        "] as const;",
        "",
        "export type GeneratedNativeAddonExport = (typeof GENERATED_NATIVE_ADDON_EXPORT_NAMES)[number];",
        "export const GENERATED_NATIVE_ADDON_EXPORTS: readonly string[] = GENERATED_NATIVE_ADDON_EXPORT_NAMES;",
        "",
        "/** Exact generated export set over handwritten, semantically meaningful binding shapes. */",
        "export type GeneratedNativeAddonDeclaration<Bindings> =",
        "  Exclude<GeneratedNativeAddonExport, keyof Bindings> extends never",
        "    ? Exclude<keyof Bindings, GeneratedNativeAddonExport> extends never",
        "      ? Bindings",
        "      : never",
        "    : never;",
        "",
    ])
    return "\n".join(lines)


def emit_conformance_json(
    manifest: dict[str, Any],
    operations: list[dict[str, Any]],
    capabilities: list[dict[str, Any]],
) -> str:
    capability_by_operation = operation_capabilities(capabilities)
    snapshot = {
        "version": manifest.get("version"),
        "errorType": manifest.get("error_type"),
        "errorFamilies": manifest.get("error_families"),
        "capabilities": capabilities,
        "operations": [
            {
                "manifestName": operation["name"],
                "facadeMethod": facade_method(operation),
                "capability": capability_by_operation[operation["name"]],
                "surface": operation["surface"],
                "nativeWired": operation["surface"] == "stable",
                "maxInputBytes": operation.get(
                    "max_input_bytes", manifest["default_max_input_bytes"]
                ),
                "maxOutputBytes": operation.get(
                    "max_output_bytes", manifest["default_max_output_bytes"]
                ),
                "input": operation["input"],
                "output": operation["output"],
                "facadeInput": operation.get("facade_input"),
                "facadeOutput": operation.get("facade_output"),
                "inputWire": {
                    "owner": wire_type_ref(operation, "input")[0],
                    "name": wire_type_ref(operation, "input")[1],
                    "repeated": wire_type_ref(operation, "input")[2],
                },
                "outputWire": {
                    "owner": wire_type_ref(operation, "output")[0],
                    "name": wire_type_ref(operation, "output")[1],
                    "repeated": wire_type_ref(operation, "output")[2],
                },
                "errors": operation["errors"],
            }
            for operation in operations
        ],
    }
    return json.dumps(snapshot, indent=2) + "\n"


def emit_rust_operations(
    manifest: dict[str, Any],
    operations: list[dict[str, Any]],
    capabilities: list[dict[str, Any]],
) -> str:
    capability_by_operation = operation_capabilities(capabilities)
    lines = [
        RUST_BANNER,
        "#![allow(dead_code)]",
        "",
        "#[derive(Clone, Copy, Debug, Eq, PartialEq)]",
        "pub(crate) enum GeneratedBridgeSurface {",
        "    Stable,",
        "    Quarantined,",
        "}",
        "",
        "#[derive(Clone, Copy, Debug, Eq, PartialEq)]",
        "pub(crate) struct GeneratedBridgeBinding {",
        "    pub manifest_name: &'static str,",
        "    pub facade_method: &'static str,",
        "    pub capability: &'static str,",
        "    pub input: &'static str,",
        "    pub output: &'static str,",
        "    pub errors: &'static str,",
        "    pub max_input_bytes: usize,",
        "    pub max_output_bytes: usize,",
        "    pub surface: GeneratedBridgeSurface,",
        "}",
        "",
        "pub(crate) const GENERATED_BRIDGE_BINDINGS: &[GeneratedBridgeBinding] = &[",
    ]
    for operation in operations:
        surface = "Stable" if operation["surface"] == "stable" else "Quarantined"
        lines.extend([
            "    GeneratedBridgeBinding {",
            f"        manifest_name: \"{operation['name']}\",",
            f"        facade_method: \"{facade_method(operation)}\",",
            f"        capability: \"{capability_by_operation[operation['name']]}\",",
            f"        input: \"{operation['input']}\",",
            f"        output: \"{operation['output']}\",",
            f"        errors: \"{operation['errors']}\",",
            f"        max_input_bytes: {operation.get('max_input_bytes', manifest['default_max_input_bytes'])},",
            f"        max_output_bytes: {operation.get('max_output_bytes', manifest['default_max_output_bytes'])},",
            f"        surface: GeneratedBridgeSurface::{surface},",
            "    },",
        ])
    lines.extend([
        "];",
        "",
        "#[cfg(test)]",
        "mod tests {",
        "    use super::*;",
        "",
        "    #[test]",
        "    fn generated_bindings_are_unique_and_typed() {",
        "        let mut names = GENERATED_BRIDGE_BINDINGS",
        "            .iter()",
        "            .map(|binding| binding.manifest_name)",
        "            .collect::<Vec<_>>();",
        "        names.sort_unstable();",
        "        names.dedup();",
        "        assert_eq!(names.len(), GENERATED_BRIDGE_BINDINGS.len());",
        "        assert!(GENERATED_BRIDGE_BINDINGS",
        "            .iter()",
        "            .all(|binding| !binding.input.is_empty()",
        "                && !binding.output.is_empty()",
        "                && !binding.errors.is_empty()));",
        "    }",
        "}",
        "",
    ])
    return "\n".join(lines)


def emit_rust_native_exports(
    manifest: dict[str, Any], operations: list[dict[str, Any]]
) -> str:
    stable = [operation for operation in operations if operation["surface"] == "stable"]
    lines = [
        RUST_BANNER,
        "#![allow(dead_code)]",
        "",
        "pub(crate) const REQUIRED_NATIVE_EXPORTS: &[(&str, &str, usize, usize)] = &[",
    ]
    for operation in stable:
        name = operation["name"]
        method = facade_method(operation)
        max_input = operation.get("max_input_bytes", manifest["default_max_input_bytes"])
        max_output = operation.get("max_output_bytes", manifest["default_max_output_bytes"])
        row = f'    ("{name}", "{method}", {max_input}, {max_output}),'
        if len(row) <= 69:
            lines.append(row)
        else:
            lines.extend([
                "    (",
                f'        "{name}",',
                f'        "{method}",',
                f"        {max_input},",
                f"        {max_output},",
                "    ),",
            ])
    lines.extend([
        "];",
        "",
        "pub(crate) fn native_wire_limits(operation: &str) -> Option<(usize, usize)> {",
        "    REQUIRED_NATIVE_EXPORTS",
        "        .iter()",
        "        .find(|entry| entry.0 == operation)",
        "        .map(|entry| (entry.2, entry.3))",
        "}",
        "",
        "#[cfg(test)]",
        "mod tests {",
        "    use super::*;",
        "",
        "    #[test]",
        "    fn generated_native_export_inventory_is_unique() {",
        "        let mut names = REQUIRED_NATIVE_EXPORTS",
        "            .iter()",
        "            .map(|entry| entry.0)",
        "            .collect::<Vec<_>>();",
        "        names.sort_unstable();",
        "        names.dedup();",
        "        assert_eq!(names.len(), REQUIRED_NATIVE_EXPORTS.len());",
        "    }",
        "}",
        "",
    ])
    return "\n".join(lines)


def emit_exports_md(operations: list[dict[str, Any]], capabilities: list[dict[str, Any]]) -> str:
    capability_by_operation = operation_capabilities(capabilities)
    lines = [
        "<!-- @generated by harness/codegen/bridge-emit.py — DO NOT EDIT. -->",
        "# native-bridge export reference",
        "",
        "Derived from `bridge-manifest.toml`. Stable operations require concrete",
        "handwritten semantic exports; quarantined operations remain replay/devtools-only.",
        "",
        "| Operation | Capability | Surface | Input | Output | Errors |",
        "|---|---|---|---|---|---|",
    ]
    for operation in operations:
        lines.append(
            f"| `{operation['name']}` | `{capability_by_operation[operation['name']]}` | "
            f"{operation['surface']} | `{operation['input']}` | `{operation['output']}` | "
            f"`{operation['errors']}` |"
        )
    lines.append("")
    return "\n".join(lines)


def generated_artifacts() -> dict[pathlib.Path, str]:
    manifest, operations, capabilities = load_manifest()
    return {
        OPS_TS: emit_operations_ts(manifest, operations, capabilities),
        SURFACES_TS: emit_surfaces_ts(operations, capabilities),
        CONF_JSON: emit_conformance_json(manifest, operations, capabilities),
        NATIVE_SURFACE_TS: emit_native_surface_ts(operations),
        RUST_OPERATIONS: emit_rust_operations(manifest, operations, capabilities),
        RUST_NATIVE_EXPORTS: emit_rust_native_exports(manifest, operations),
        EXPORTS_MD: emit_exports_md(operations, capabilities),
    }


def main(arguments: list[str]) -> int:
    if len(arguments) != 1 or arguments[0] not in {"--write", "--check"}:
        print(__doc__)
        return 2
    try:
        artifacts = generated_artifacts()
    except (OSError, ValueError, tomllib.TOMLDecodeError) as cause:
        print(f"Bridge codegen: invalid manifest: {cause}")
        return 1
    if arguments[0] == "--write":
        for path, content in artifacts.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(REPO)}")
        return 0
    stale = []
    for path, content in artifacts.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            stale.append(path.relative_to(REPO))
    if stale:
        print("Bridge codegen: STALE — run `python3 harness/codegen/bridge-emit.py --write`")
        for path in stale:
            print(f"  drift: {path}")
        return 1
    print(f"Bridge codegen: OK ({len(artifacts)} artifacts match the manifest)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
