#!/usr/bin/env python3
"""Bridge glue emitter — generates the boring glue from the curated manifest.

Middle-path codegen (ADR 0006 / MANIFEST-FORMAT.md §3): one operation in, one
artifact entry out. No reflection, no dynamic dispatch. Semantic operation bodies
stay hand-written; this only emits the mechanical, diffable glue.

Generated artifacts (committed, not hand-edited):
  - ts/packages/runtime-bridge/src/generated/operations.ts   (typed op registry)
  - ts/packages/runtime-bridge/src/generated/conformance.json (signature snapshot)
  - engine-rs/crates/bridge/native-bridge/src/generated/EXPORTS.md (napi signature ref)

Usage:
  bridge-emit.py --write    # (re)write generated files
  bridge-emit.py --check    # fail if committed files differ from a fresh emit
"""
import sys
import json
import pathlib
import tomllib

REPO = pathlib.Path(__file__).resolve().parents[2]
MANIFEST = REPO / "engine-rs/crates/bridge/runtime-bridge-api/bridge-manifest.toml"

OPS_TS = REPO / "ts/packages/runtime-bridge/src/generated/operations.ts"
CONF_JSON = REPO / "ts/packages/runtime-bridge/src/generated/conformance.json"
EXPORTS_MD = REPO / "engine-rs/crates/bridge/native-bridge/src/generated/EXPORTS.md"

GEN_BANNER_TS = "// @generated by harness/codegen/bridge-emit.py — DO NOT EDIT.\n" \
                "// Source of truth: engine-rs/crates/bridge/runtime-bridge-api/bridge-manifest.toml\n" \
                "// Regenerate: python3 harness/codegen/bridge-emit.py --write\n"


def snake_to_camel(name: str) -> str:
    head, *rest = name.split("_")
    return head + "".join(p.capitalize() for p in rest)


def load_ops():
    with open(MANIFEST, "rb") as f:
        data = tomllib.load(f)
    return data.get("manifest", {}), data.get("operation", [])


def emit_operations_ts(ops) -> str:
    lines = [GEN_BANNER_TS, ""]
    lines.append("export type BridgeSurface = 'stable' | 'quarantined';")
    lines.append("")
    lines.append("export interface BridgeOperation {")
    lines.append("  /** snake_case name, identical to bridge-manifest.toml `[[operation]].name`. */")
    lines.append("  readonly manifestName: string;")
    lines.append("  /** camelCase method on the `RuntimeBridge` facade. */")
    lines.append("  readonly facadeMethod: string;")
    lines.append("  readonly surface: BridgeSurface;")
    lines.append("}")
    lines.append("")
    lines.append("export const MANIFEST_OPERATIONS: readonly BridgeOperation[] = [")
    for op in ops:
        name = op["name"]
        lines.append(
            f"  {{ manifestName: '{name}', "
            f"facadeMethod: '{snake_to_camel(name)}', "
            f"surface: '{op['surface']}' }},"
        )
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def emit_conformance_json(manifest, ops) -> str:
    snapshot = {
        "version": manifest.get("version"),
        "errorType": manifest.get("error_type"),
        "operations": [
            {
                "manifestName": op["name"],
                "facadeMethod": snake_to_camel(op["name"]),
                "surface": op["surface"],
                "input": op["input"],
                "output": op["output"],
                "errors": op["errors"],
            }
            for op in ops
        ],
    }
    return json.dumps(snapshot, indent=2) + "\n"


def emit_exports_md(ops) -> str:
    lines = [
        "<!-- @generated by harness/codegen/bridge-emit.py — DO NOT EDIT. -->",
        "# native-bridge `#[napi]` export reference",
        "",
        "Derived from `bridge-manifest.toml`. The hand-written semantic bodies in",
        "`src/lib.rs` must expose exactly these operations (one-in/one-out). Quarantined",
        "operations are replay/devtools-only.",
        "",
        "| Operation | Surface | Input | Output | Errors |",
        "|---|---|---|---|---|",
    ]
    for op in ops:
        lines.append(
            f"| `{op['name']}` | {op['surface']} | `{op['input']}` | "
            f"`{op['output']}` | `{op['errors']}` |"
        )
    lines.append("")
    return "\n".join(lines)


def main(argv) -> int:
    if len(argv) != 1 or argv[0] not in ("--write", "--check"):
        print(__doc__)
        return 2
    mode = argv[0]
    manifest, ops = load_ops()
    artifacts = {
        OPS_TS: emit_operations_ts(ops),
        CONF_JSON: emit_conformance_json(manifest, ops),
        EXPORTS_MD: emit_exports_md(ops),
    }

    if mode == "--write":
        for path, content in artifacts.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            print(f"wrote {path.relative_to(REPO)}")
        return 0

    # --check
    stale = []
    for path, content in artifacts.items():
        current = path.read_text() if path.exists() else None
        if current != content:
            stale.append(path.relative_to(REPO))
    if stale:
        print("Bridge codegen: STALE — regenerate with `python3 harness/codegen/bridge-emit.py --write`")
        for p in stale:
            print(f"  drift: {p}")
        return 1
    print(f"Bridge codegen: OK ({len(artifacts)} artifacts match the manifest)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
